### ISSUE TITLE
关于数据集和读取数据集

### ISSUE THREAD

**Issue by Dowson0** [754131799/DeepSF-4mC#1]
文章中提到的数据集是txt形式的，为什么会在main文件里面使用get_fasta来读取文件。另外您的fs和tools文件并没有分享。如果可以的话请分享一下，谢谢

**Comment by 754131799** [comment]
在python读取序列数据文件时，fasta文件和txt文件没有本质区别，只要其内容符合fasta格式即可。此外，序列预测领域的已发表文献中有相当大的比例均使用txt文件存储fasta格式，因此你的质疑并不合理。另外，tools工具包仅涉及一些简单的容易实现的功能函数比如ACC，AUC等，以及python读取文本文件，而不涉及手稿中的关键技术（如迁移学习模型和集成学习模块）。其中fs模块涉及序列编码方式的ilearn版本的实现，这在手稿中也提及了，因此你从ilearn也可以下载到这些编码方式的完整代码。同时，我们更新上传了fs和tools在代码官网的tools文件夹当中，方便您复现使用。如果您觉得我们的工作对您有用，请引用"DeepSF-4mC: A deep learning model for predicting DNA cytosine 4mC methylation sites leveraging sequence features"。

**Comment by Dowson0** [comment]
感谢您的帮助，祝学术长虹
